# EVENT WITH ALL THE DATA
POST http://localhost:3000/api/events
content-type: application/json

{
    "name": "Nuevo evento",
    "location": "Teatro",
    "description": "Este evento es nuevo nuevo",
    "photoUrl": "https://imagekit.androidphoria.com/wp-content/uploads/como-buscar-una-imagen-en-facebook-con-una-foto.jpg",
    "dates": [
        {
            "datetime": "2021-05-26T23:00:00.000Z",
            "price": 200
        },
        {
            "datetime": "Mon, 25 Dec 2021 20:30:00 GMT",
            "price": 300
        }
    ]
}


###

# EVENT WITHOUT NAME DATA
POST http://localhost:3000/api/events
content-type: application/json

{
    "location": "Teatro",
    "description": "Este evento es nuevo",
    "photoUrl": "https://imagekit.androidphoria.com/wp-content/uploads/como-buscar-una-imagen-en-facebook-con-una-foto.jpg",
    "dates": [
        {
            "datetime": "Mon, 25 Dec 2021 13:30:00 GMT",
            "price": 200
        },
        {
            "datetime": "Mon, 25 Dec 2021 20:30:00 GMT",
            "price": 300
        }
    ]
}

###

# EVENT WITHOUT LOCATION DATA
POST http://localhost:3000/api/events
content-type: application/json

{
    "name": "Evento sin location",
    "description": "Este evento es nuevo",
    "photoUrl": "https://imagekit.androidphoria.com/wp-content/uploads/como-buscar-una-imagen-en-facebook-con-una-foto.jpg",
    "dates": [
        {
            "datetime": "Mon, 25 Dec 2021 13:30:00 GMT",
            "price": 200
        },
        {
            "datetime": "Mon, 25 Dec 2021 13:30:00 GMT",
            "price": 300
        }
    ]
}