# GET ALL EVENTS
GET http://localhost:3000/api/events

###

# GET EVENTS BY DATE
GET http://localhost:3000/api/events?startDate=Mon, 01 Aug 2021 00:00:00 GMT&endDate=Mon, 01 Aug 2021 23:59:59 GMT

###

# GET EVENTS BY NAME
GET http://localhost:3000/api/events?name=agos

###

# GET EVENTS HIGHLIGHTED
GET http://localhost:3000/api/events?highlighted=true