PUT http://localhost:3000/api/events/61182ecc69c6284005a1bb78
content-type: application/json

{
    "name": "Evento modificadoo",
    "dates": [
        {
            "datetime": "2021-05-26T23:00:00.000Z",
            "price": 400
        }
    ],
    "location": "CINE"
}