PUT http://localhost:3000/api/events/61196fcb70a06b0234855df9
content-type: application/json

{
    "name": "Evento de diciembre",
    "description": "Este evento fue modificado",
    "dates": [
        {
            "datetime": "Mon, 01 Dec 2021 20:30:00 GMT",
            "price": 400
        },
        {
            "datetime": "Mon, 01 Dec 2021 22:30:00 GMT",
            "price": 400
        }
    ],
    "location": "CINE",
    "highlighted": false
}